version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=shopping_web_service
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "3306:3306"
    volumes:
      - ./resources/db-migrations:/docker-entrypoint-initdb.d/
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  redis:
    container_name: "redis_docker"
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  mysql-data: